<a href="https://colab.research.google.com/github/Hariklk/Hariklk/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [26]:
import numpy as np
a  = np.array([1,2,3,])
print(a[0])

1


In [25]:
a[1]

np.int64(2)

In [34]:
import time
import sys
b = range(1000)
print(sys.getsizeof(b)*len(b))

48000


In [ ]:
c=np.array.range(1000)
print(c.itemsize)
a.shape


In [50]:
o = np.array([[1,2,3],[3,5,6],[2,3,4]],dtype=np.float64)
print(o)
print(type(o))
o.itemsize
o.shape

[[1. 2. 3.]
 [3. 5. 6.]
 [2. 3. 4.]]
<class 'numpy.ndarray'>


(3, 3)

In [74]:
o = np.array([[1,2,3],[3,5,6],[2,3,4]],dtype=np.complex128)
print(o)
print(type(o))
o.itemsize
o.shape
o.ndia

[[1.+0.j 2.+0.j 3.+0.j]
 [3.+0.j 5.+0.j 6.+0.j]
 [2.+0.j 3.+0.j 4.+0.j]]
<class 'numpy.ndarray'>


AttributeError: 'numpy.ndarray' object has no attribute 'ndia'

In [73]:
o.ndia

AttributeError: 'numpy.ndarray' object has no attribute 'ndia'

In [57]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [67]:
#np.ones((2,5))
print(np.char.title("numpy test hello every one"))


Numpy Test Hello Every One


In [68]:
print(np.char.split("numpy test hello every one"))

['numpy', 'test', 'hello', 'every', 'one']


In [70]:
print(np.char.upper("numpy test hello every one"))
print(np.char.lower("numpy test hello every one"))

NUMPY TEST HELLO EVERY ONE
numpy test hello every one


In [72]:
print(np.char.splitlines("numpy test \n hello every one"))

['numpy test ', ' hello every one']


In [75]:
print(np.char.capitalize("numpy test hello every one"))

Numpy test hello every one
